title: Luz Angélica Caudillo-Mata, PhD
author: 
email: lcaudill@eoas.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
  Computational Scientist | Applied Mathematician | Industrial Postdoctoral Fellow | AI Researcher | Bridge Builder

# social links
twitter_username: lacaudillomata
github_username:  lacmajedrez

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
